### ISSUE TITLE
Suggest remove those rules.

### ISSUE THREAD

**Issue by wufaxiayudeyun** [huiyifyj/Proxy-pac.js#2]
Remove those rules.
Link[3766](https://github.com/huiyifyj/Proxy-pac.js/blob/86243e5aee04f0cdeb0bb7bb86f84cf704f427f4/proxy-pac.dev.js#L3766) to [3818](https://github.com/huiyifyj/Proxy-pac.js/blob/86243e5aee04f0cdeb0bb7bb86f84cf704f427f4/proxy-pac.dev.js#L3818).
Those rules is useless for using Google search.

**Comment by huiyifyj** [comment]
Thanks for your suggestion.
For this pac file, those rules more beneficial. And this file is not large.

**Comment by wufaxiayudeyun** [comment]
You can remove part of those rule.
Such as, "q=triangle", "q%3DTriangle".

**Comment by huiyifyj** [comment]
Well, so I do.
