### ISSUE TITLE
Move twitter domains in place

### ISSUE THREAD

**Issue by wufaxiayudeyun** [huiyifyj/Proxy-pac.js#3]
As your [project](https://github.com/huiyifyj/Proxy-pac.js/projects/2), you should move domains about Twitter Inc in place.
Link [3243](https://github.com/huiyifyj/Proxy-pac.js/blob/7344ffe436d2c637d0cc5cd0fc19e0f4758a09c0/proxy-pac.dev.js#L3243) to [3251](https://github.com/huiyifyj/Proxy-pac.js/blob/7344ffe436d2c637d0cc5cd0fc19e0f4758a09c0/proxy-pac.dev.js#L3251).

**Comment by wufaxiayudeyun** [comment]
According to whois information, link [3246](https://github.com/huiyifyj/Proxy-pac.js/blob/7344ffe436d2c637d0cc5cd0fc19e0f4758a09c0/proxy-pac.dev.js#L3246).
"twittbot.net" have no concern with Twitter.

**Comment by huiyifyj** [comment]
Do it. 
By the way, I add and other domains.
